language: node_js
node_js:
  - 14
jobs:
  install:
    - yarn install
  script:
    - yarn generate
    - pwd
    - ls
    - mv public/ /tmp/public
  before_deploy:
    - pwd
    - ls
  deploy:
    provider: pages
    local_dir: /tmp/public
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    on:
      branch: master
env:
  global:
    - secure: MLlxBBR1L0z68wAhV76jR73+uBaFaOukzfb9l806nb6trU3fno/aCZbRK9ebjZsp0gCeKcnpRYluPlma1X9oWQ1ccKNQVoNj5YYrg23cOebB4oxVUsVqyJfT8z6ZB1gupJb8yisXNLU/qzbvPFk3R2Qzi5B8nQY0Eb1DEbw3v5Zh/XZrtiSxHJ6OpxYQmsHxmlcAMfg4Dt6THiT65WuXsW5x5H4L1H6qUZ0aAKEjzKoQuppOMieuFS+kEdBWBLdYmYvIpA/ckN5vkjGh45eJMfmirOaIuZ175uhtmiEGwmbL5hEYufGj4r2TsGtK5i4P1nR91IHwz1/w+/REC9jXcyG2O0pvdkLLXxOyJXXeI5jmeBtRnUMiOoxTVdO0NboVrG3d6Or0bVfLjcNT/EKGCahuIMyRPx1izJr1ZJ9gjzw/g03Sz6gQ0U2D/jd44iWHb6G5/4russ4h0Ynru+fTpsoCu/Glg2VaILrrihrWKJPbU4oU5F1YBihxvYmAExsLSfjHX/efjYvLsekHa9EDnPMnoKDkmrtk9fwUpztwuCyTdUFOb4u7KrkfeDV3ETwcZEwyjRYzWAUIWW4q9EsfZKs1XxqQKTWBm5Om4OQ7O5SeKGTcYkFjs8dC8UlKvw3Iu39WI+E/5uuZlwHZ+2NSkEBnsziBrwuBVWi8NKb9uQU=
