# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# ----------------------------------------------------------
# Site
title: Kavience
subtitle: blog
author: Kavience
language: zh-CN
timezone: asia/shanghai
description: "kavience 的博客, 专注于前端开发, web开发, 编程技术"
keyword: "kavience,javascript,前端开发,php,react,kavience博客"
# If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.kavience.com/ # Note: don't forget to modify the CNAME file to your url
root: /
permalink: :category/:translate_title.html # Use hexo-translate-title

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  wrap: false
  hljs: false

# Date / Time format
# Hexo uses Moment.js to parse and display date
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
per_page: 6 # Set per_page to 0 to disable pagination

# ----------------------------------------------------------
# Plugins: https://hexo.io/plugins/

# Themes: https://hexo.io/themes/
theme: easy-read

# Markdown-it config
# https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: "“”‘’"
  anchors:
    level: 2 # Minimum level for ID creation. (Ex. h2 to h6)
    collisionSuffix: "v" # A suffix that is prepended to the number given if the ID is repeated
    permalink: false # If `true`, creates an anchor tag with a permalink besides the heading
    permalinkClass: header-anchor # Class used for the permalink anchor tag
    permalinkSymbol: "" # The symbol used to make the permalink

# hexo-generator-archive
# https://github.com/hexojs/hexo-generator-archive
archive_generator:
  per_page: 6
  yearly: true
  monthly: true
  daily: false

# hexo-generator-feed
# https://github.com/hexojs/hexo-generator-feed
feed:
  type: atom
  path: feed
  limit: false

# Share
# Reference: https://github.com/overtrue/share.js
share: true

# hexo-generator-seo-friendly-sitemap
# https://github.com/ludoviclefevre/hexo-generator-seo-friendly-sitemap#readme
sitemap:
  path: sitemap.xml

# hexo-translate-title
# https://github.com/cometlj/hexo-translate-title#readme
translate_title:
  translate_way: google # google,youdao,baidu_with_appid,baidu_no_appid
  youdao_api_key: "" # Your youdao_api_key
  youdao_keyfrom: xxxx-blog # Your youdao_keyfrom
  is_need_proxy: false # true | false
  # proxy_url: http://127.0.0.1:7890 # Your proxy_url
  baidu_appid: "" # Your baidu_appid
  baidu_appkey: "" # Your baidu_appkey
  rewrite: false # is rewrite true | false

# hexo-generator-searchdb
# https://github.com/next-theme/hexo-generator-searchdb#readme
search:
  path: search.json
  field: post
  content: true
  format: html

# hexo-tag-cloud
# https://github.com/D0n9X1n/hexo-tag-cloud#readme
tag_cloud:
  textFont: Trebuchet MS, Helvetica
  textColor: "#337ab7"
  textHeight: 25
  outlineColor: "#f1e5c9"
  maxSpeed: 0.08
